
import type { Metadata } from "next";
import { Acme, Open_Sans } from "next/font/google";
import "./globals.css";

const acme = Acme({
  variable: "--font-acme",
  subsets: ["latin"],
  weight: "400",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${acme.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
